### ISSUE TITLE
Missing localized assemblies from referenced projects

### ISSUE THREAD

**Issue by Matthei52** [tenekon/Tenekon.MSBuild.Packaging.ProjectBuildInPackage#4] opened 2024-09-18 07:28 UTC
This issue was already raised once at the old project (https://github.com/teneko/Teronis.DotNet/issues/16). But since the ProjectBuildInPackage part was outsourced into this project. I figured creating a new Issue was cleaner.

I ran into the bug that localized assemblies were missing in the created NuGet package. This seems to happen, once more than one project with localization is referenced. Resulting in the error NU5118 and ClassLibrary3.resources.dll not being added to the package:
`2>NuGet.Build.Tasks.Pack.targets(221,5): Warning NU5118 : File "D:\Work\LocalizationBugRepro\LocalizationBugRepro\ClassLibrary3\bin\Debug\net8.0\en\ClassLibrary3.resources.dll"is not added because the package already contains file "lib\net8.0\en\"`

I managed to create a minimal reproduction solution and attached it here:
[LocalizationBugRepro.zip](https://github.com/user-attachments/files/17039368/LocalizationBugRepro.zip)

The project structure essentially looks like this:
```
ClassLibrary1 (For creating the nuget package, references ClassLibrary2 and ClassLibrary3)
│   Resources1.resx (Note: localization assemblies of this project do not cause a conflict)
│   Resources1.en.resx
│   Resources1.Designer.cs

ClassLibrary2 (Only the localization assemblies of this project will be added)
│   Resources2.resx
│   Resources2.en.resx
│   Resources2.Designer.cs

ClassLibrary3 (The localization assemblies of this project will throw the error)
│   Resources3.resx
│   Resources3.en.resx
│   Resources3.Designer.cs
```
Should it be possible to combine multiple localized projects into one package? Or am i just using it wrong?

**Comment by teneko** [comment] 2024-09-18 19:56
Thanks for the reproduction sample.

When running the build process, I made the following observation:

```
  [Teronis.MSBuild.Packaging.ProjectBuildInPackage] Thanks for using my package. <3
  [Teronis.MSBuild.Packaging.ProjectBuildInPackage] Copy ..\ClassLibrary2\bin\Debug\net8.
  0\ClassLibrary2.dll (local) to .\ (package)
  [Teronis.MSBuild.Packaging.ProjectBuildInPackage] Copy ..\ClassLibrary3\bin\Debug\net8.
  0\ClassLibrary3.dll (local) to .\ (package)
  [Teronis.MSBuild.Packaging.ProjectBuildInPackage] Copy ..\ClassLibrary2\bin\Debug\net8.
  0\ClassLibrary2.pdb (local) to .\ (package)
  [Teronis.MSBuild.Packaging.ProjectBuildInPackage] Copy ..\ClassLibrary3\bin\Debug\net8.
  0\ClassLibrary3.pdb (local) to .\ (package)
  [Teronis.MSBuild.Packaging.ProjectBuildInPackage] Copy ..\ClassLibrary2\bin\Debug\net8.
  0\en\ClassLibrary2.resources.dll (local) to .\en\ (package)
  [Teronis.MSBuild.Packaging.ProjectBuildInPackage] Copy ..\ClassLibrary3\bin\Debug\net8.
  0\en\ClassLibrary3.resources.dll (local) to .\en\ (package)
```

What seems to be very interesting is, that `..\ClassLibrary3\bin\Debug\net8.0\en\ClassLibrary3.resources.dll` is recognized, but for some reason the file is not taken into account for the NuGet package creation. When commenting out the ClassLibrary2 ProjectReference, then the localization assemblies of ClassLibrary3 are now in the NuGet package. What seems to be much more interesting is, that when you swap the ProjectReferences. Then indeed, ClassLibrary3.dll is now in the package, but en/ClassLibrary2.dll not, where before that ClassLibrary2.dll was in the package, but en/ClassLibrary3.dll not.

The reason this behavior is occurring is that BuildOutputInPackage elements were grouped by TargetPath and NOT by TargetPath and (implicitly) Identity. Compare the following two images:
![1-1](https://github.com/user-attachments/assets/d55916e8-3b20-4a39-872b-ba37d5bbe946)
![1-2](https://github.com/user-attachments/assets/f7258790-e3c6-4f9c-aaec-3ca61a492d01)

And the most confusing behaviour is, that while even using `Include="@(_ReferenceCopyLocalPaths)"` and the resulting elements were inheriting the elements of each element of_ReferenceCopyLocalPaths, they didn't count into the grouping, which is SUPER interesting. Whatsoever.

The solution is to specify a so called first class attribute (!?!??!?!) to get count into the grouping behaviour, e.g. `<BuildOutputInPackage Include="@(_ReferenceCopyLocalPaths)" ProjectBuildInPackageReasonToExpandItemGroupElement="%(_ReferenceCopyLocalPaths.Identity)" TargetPath="%(_ReferenceCopyLocalPaths.DestinationSubDirectory)" />`

I am going to upload a bug fix in the next days. 🙂

**Comment by teneko** [comment] 2024-09-19 17:55
A fix has been uploaded. See [NuGet Package 1.0.2](https://www.nuget.org/packages/Teronis.MSBuild.Packaging.ProjectBuildInPackage/1.0.2).

**Closed as completed by teneko** 2024-09-19 17:55 UTC
Labels: bug
